name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
    - name: Build the code
      run: |
        time ../v/v build config_http
    - name: Results
      run: |
        ./a.out
