name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        echo $GITHUB_WORKSPACE
        pwd
    - name: Build V
      run: |
        git clone --depth 1 https://github.com/vlang/v ../v
        cd ../v
        make
    - name: Build the code
      run: |
        pwd
        # echo "hello" > $HOME/apa.txt
        # echo $HOME/apa.txt
        time ../v/v build config_http
    - name: Results
      run: |
        pwd
        export HOME=$GITHUB_WORKSPACE
        ./a.out
